common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/',views.signup, name='signup')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/',include('common.urls')),
    path('',base_views.index, name='index')
]

handler404 = 'common.views.page_not_found'

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    path('',base_views.index, name='index'),
    path('<int:question_id>/',base_views.detail, name='detail'),


    path('question/create/',question_views.question_create,name='question_create'),
    path('question/modify/<int:question_id>/',question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',question_views.question_delete, name='question_delete'),

    path('answer/create/<int:question_id>/',answer_views.answer_create,name='answer_create'),
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete, name='answer_delete'),

    path('comment/create/question/<int:question_id>/',comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q, Count

from ..models import Question


def index(request):
    """
    pybo 목록 출력
    """
    # print(request.GET) == <QueryDict: {'page': ['4']}>
    page = request.GET.get('page','1')
    kw = request.GET.get('kw','')
    so = request.GET.get('so','recent')

    """
    annotate 함수는 Question 모델의 기존 필드인
     author, subject, content, create_date, modify_date, voter에 질문의 
     추천 수에 해당하는 num_voter 필드를 임시로 추가해 주는 함수이다. 
     이렇게 annotate 함수로 num_voter 필드를 추가하면 filter 함수나 order_by 함수에서 num_voter 필드를 사용할 수 있게 된다.
      여기서 num_voter는 Count('voter')와 같이 Count 함수를 사용하여 만들었다.
    """
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter','-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer','-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')

    """
    localhost:8000/pybo/?page=1
    get('page', '1')에서 '1'은 /pybo/ URL처럼 page 파라미터가 없는 URL을 위해 기본값으로 1을 지정한 것이다
    """
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw)|
            Q(content__icontains=kw)|
            Q(author__username__icontains=kw)|
            Q(answer__author__username__icontains=kw)
            ).distinct()
        

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    
   

    context = {'question_list':page_obj, 'page':page, 'kw':kw, 'so':so}
    
    return render(request, 'pybo/question_list.html',context)

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    
    return render(request, 'pybo/question_detail.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang='ko'>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}  
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{user.username}}(로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>